name: Multi Job Example
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Running tests..."

  example:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "Printing environment variables"
          printenv

      - name: Print current working directory
        run: |
          echo "Current working directory:"
          pwd

      - name: List files in the current directory
        run: |
          echo "Listing files in the current directory:"
          ls -alh
